### ISSUE TITLE
Flag to switch between using super structure or fully-connected graph for A* on local cluster 

### ISSUE THREAD

**Issue by steven-causalens** [ignavierng/local-astar#1]
Hello,

First of all thanks you for making your implementation of Local A* public. I'm looking forward to using it for my use-cases, although I'm currently just reading through the code.

I noticed that in the two_step_search() method of [local-astar/src/search/local_search.py](https://github.com/ignavierng/local-astar/blob/master/src/search/local_search.py) there is no flag that decides between using super structures and using the fully-connected graph when applying A* to a local cluster. In fact, currently the code does *both* computations, which seems inefficient, with the fully-connected graph computation overriding the super structure computation. Would it make sense to add a flag / switch here?

Here is the code from lines 114-119 of [local-astar/src/search/local_search.py](https://github.com/ignavierng/local-astar/blob/master/src/search/local_search.py) that I'm referring to:

```
    dag_est, search_stats_ = exact_search(X_nodes, super_graph, search_method, use_path_extension,
                                          use_k_cycle_heuristic, k, verbose, include_graph)
    search_stats.update(search_stats_)
    # Search two-step neighbors without super-structure (less efficient)
    dag_est, search_stats_ = exact_search(X_nodes, None, search_method, use_path_extension,
                                          use_k_cycle_heuristic, k, verbose, include_graph)
```

**Comment by ignavierng** [comment]
Thank you for the great idea. The part of the code for `Search two-step neighbors without super-structure (less efficient)` was supposed to be commented. Adding a flag is indeed better, and I have incorporated your suggestion here 473ff5a4a567a95bed0d28090b130a2a67665016.
